version: "3.7"

services:
  database:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  sidekiq:
    build: ./app
    restart: always
    command: bundle exec sidekiq

  redis:
    image: redis:5.0.5-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: ./app
    restart: always
    command: bash -c "rm -f /app/tmp/pids/server.pid && foreman start -f /app/Procfile"
    volumes:
      - ./app:/app
      - /app/tmp
      - rails_log:/app/log
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database
    tty: true
    stdin_open: true

volumes:
  database:
  redis:
  rails_log: