version: "3.7"

services:
  database:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  app:
    build: ./app
    command: bash -c "rm -f /app/tmp/pids/server.pid && foreman start -f /app/Procfile"
    volumes:
      - ./app:/app
      - /app/tmp
      - rails_log:/app/log
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  database:
  rails_log: